version: '3.7'
services:
  crypto:
    command: 'yarn start'
    container_name: crypto
    environment:
      NODE_ENV: docker
    image: keymux/docker-ubuntu-nvm-yarn:latest
    networks:
      - local
      - internet
      - rproxy_crypto
    restart: unless-stopped
    stop_grace_period: 0s
    volumes:
      - .:/app
      - /tmp/null:/app/.nyc_output:ro
      - /tmp/null:/app/coverage:ro
    working_dir: /app
  db:
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: test-password
    image: postgres
    networks:
      - local
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
networks:
  local:
    internal: true
  internet:
  rproxy_crypto:
    external: true
