INSERT INTO
  "coins"
  ("symbol", "name", "slug")
VALUES
  ('BTC', 'Bitcoin', 'bitcoin'),
  ('ETH', 'Ethereum', 'ethereum'),
  ('XRP', 'XRP', 'ripple'),
  ('BCH', 'Bitcoin Cash', 'bitcoin-cash'),
  ('LTC', 'Litecoin', 'litecoin'),
  ('USDT', 'Tether', 'tether'),
  ('EOS', 'EOS', 'eos'),
  ('BNB', 'Binance Coin', 'binance-coin'),
  ('BSV', 'Bitcoin SV', 'bitcoin-sv'),
  ('XLM', 'Stellar', 'stellar'),
  ('XMR', 'Monero', 'monero'),
  ('ADA', 'Cardano', 'cardano'),
  ('LEO', 'UNUS SED LEO', 'unus-sed-leo'),
  ('TRX', 'TRON', 'tron'),
  ('DASH', 'Dash', 'dash'),
  ('ETC', 'Ethereum Classic', 'ethereum-classic'),
  ('XTZ', 'Tezos', 'tezos'),
  ('MIOTA', 'IOTA', 'iota'),
  ('LINK', 'Chainlink', 'chainlink'),
  ('NEO', 'NEO', 'neo'),
  ('MKR', 'Maker', 'maker'),
  ('USDC', 'USD Coin', 'usd-coin'),
  ('XEM', 'NEM', 'nem'),
  ('ATOM', 'Cosmos', 'cosmos'),
  ('ONT', 'Ontology', 'ontology'),
  ('CRO', 'Crypto.com Chain', 'crypto-com-chain'),
  ('ZEC', 'Zcash', 'zcash'),
  ('DOGE', 'Dogecoin', 'dogecoin'),
  ('VSYS', 'V Systems', 'v-systems'),
  ('DCR', 'Decred', 'decred'),
  ('LAMB', 'Lambda', 'lambda'),
  ('VET', 'VeChain', 'vechain'),
  ('BAT', 'Basic Attention Token', 'basic-attention-token'),
  ('QTUM', 'Qtum', 'qtum'),
  ('PAX', 'Paxos Standard Token', 'paxos-standard-token'),
  ('TUSD', 'TrueUSD', 'trueusd'),
  ('BTG', 'Bitcoin Gold', 'bitcoin-gold'),
  ('HT', 'Huobi Token', 'huobi-token'),
  ('BTM', 'Bytom', 'bytom'),
  ('HEDG', 'HedgeTrade', 'hedgetrade'),
  ('OMG', 'OmiseGO', 'omisego'),
  ('RVN', 'Ravencoin', 'ravencoin'),
  ('LSK', 'Lisk', 'lisk'),
  ('NANO', 'Nano', 'nano'),
  ('KCS', 'KuCoin Shares', 'kucoin-shares'),
  ('BCD', 'Bitcoin Diamond', 'bitcoin-diamond'),
  ('ALGO', 'Algorand', 'algorand'),
  ('THETA', 'THETA', 'theta'),
  ('INB', 'Insight Chain', 'insight-chain'),
  ('WAVES', 'Waves', 'waves'),
  ('BTT', 'BitTorrent', 'bittorrent'),
  ('HOT', 'Holo', 'holo'),
  ('NRG', 'Energi', 'energi'),
  ('ICX', 'ICON', 'icon'),
  ('DGB', 'DigiByte', 'digibyte'),
  ('EGT', 'Egretia', 'egretia'),
  ('ZRX', '0x', '0x'),
  ('BTS', 'BitShares', 'bitshares'),
  ('HC', 'HyperCash', 'hypercash'),
  ('NPXS', 'Pundi X', 'pundi-x'),
  ('REP', 'Augur', 'augur'),
  ('AOA', 'Aurora', 'aurora'),
  ('IOST', 'IOST', 'iostoken'),
  ('MONA', 'MonaCoin', 'monacoin'),
  ('NEX', 'Nash Exchange', 'nash-exchange'),
  ('KMD', 'Komodo', 'komodo'),
  ('DAI', 'Dai', 'dai'),
  ('QNT', 'Quant', 'quant'),
  ('MAID', 'MaidSafeCoin', 'maidsafecoin'),
  ('SC', 'Siacoin', 'siacoin'),
  ('XVG', 'Verge', 'verge'),
  ('RIF', 'RIF Token', 'rif-token'),
  ('ZIL', 'Zilliqa', 'zilliqa'),
  ('AE', 'Aeternity', 'aeternity'),
  ('GNT', 'Golem', 'golem-network-tokens'),
  ('ETP', 'Metaverse ETP', 'metaverse'),
  ('STEEM', 'Steem', 'steem'),
  ('SNT', 'Status', 'status'),
  ('ARDR', 'Ardor', 'ardor'),
  ('REN', 'Ren', 'ren'),
  ('QKC', 'QuarkChain', 'quarkchain'),
  ('MCO', 'Crypto.com', 'crypto-com'),
  ('GXC', 'GXChain', 'gxchain'),
  ('ABBC', 'ABBC Coin', 'abbc-coin'),
  ('ENJ', 'Enjin Coin', 'enjin-coin'),
  ('WTC', 'Waltonchain', 'waltonchain'),
  ('XZC', 'Zcoin', 'zcoin'),
  ('SNX', 'Synthetix Network Token', 'synthetix-network-token'),
  ('SOLVE', 'SOLVE', 'solve'),
  ('WAXP', 'WAX', 'wax'),
  ('BEAM', 'Beam', 'beam'),
  ('WAN', 'Wanchain', 'wanchain'),
  ('STRAT', 'Stratis', 'stratis'),
  ('ELF', 'aelf', 'aelf'),
  ('ELA', 'Elastos', 'elastos'),
  ('GRIN', 'Grin', 'grin'),
  ('NEXO', 'Nexo', 'nexo'),
  ('PAI', 'Project Pai', 'project-pai'),
  ('ETN', 'Electroneum', 'electroneum'),
  ('PZM', 'PRIZM', 'prizm')
