INSERT INTO
  "coins"
  ("id", "symbol", "name", "slug")
VALUES
  (0, 'BTC', 'Bitcoin', 'bitcoin'),
  (1, 'ETH', 'Ethereum', 'ethereum'),
  (2, 'XRP', 'XRP', 'ripple'),
  (3, 'BCH', 'Bitcoin Cash', 'bitcoin-cash'),
  (4, 'LTC', 'Litecoin', 'litecoin'),
  (5, 'USDT', 'Tether', 'tether'),
  (6, 'EOS', 'EOS', 'eos'),
  (7, 'BNB', 'Binance Coin', 'binance-coin'),
  (8, 'BSV', 'Bitcoin SV', 'bitcoin-sv'),
  (9, 'XLM', 'Stellar', 'stellar'),
  (10, 'XMR', 'Monero', 'monero'),
  (11, 'ADA', 'Cardano', 'cardano'),
  (12, 'LEO', 'UNUS SED LEO', 'unus-sed-leo'),
  (13, 'TRX', 'TRON', 'tron'),
  (14, 'DASH', 'Dash', 'dash'),
  (15, 'ETC', 'Ethereum Classic', 'ethereum-classic'),
  (16, 'XTZ', 'Tezos', 'tezos'),
  (17, 'MIOTA', 'IOTA', 'iota'),
  (18, 'LINK', 'Chainlink', 'chainlink'),
  (19, 'NEO', 'NEO', 'neo'),
  (20, 'MKR', 'Maker', 'maker'),
  (21, 'USDC', 'USD Coin', 'usd-coin'),
  (22, 'XEM', 'NEM', 'nem'),
  (23, 'ATOM', 'Cosmos', 'cosmos'),
  (24, 'ONT', 'Ontology', 'ontology'),
  (25, 'CRO', 'Crypto.com Chain', 'crypto-com-chain'),
  (26, 'ZEC', 'Zcash', 'zcash'),
  (27, 'DOGE', 'Dogecoin', 'dogecoin'),
  (28, 'VSYS', 'V Systems', 'v-systems'),
  (29, 'DCR', 'Decred', 'decred'),
  (30, 'LAMB', 'Lambda', 'lambda'),
  (31, 'VET', 'VeChain', 'vechain'),
  (32, 'BAT', 'Basic Attention Token', 'basic-attention-token'),
  (33, 'QTUM', 'Qtum', 'qtum'),
  (34, 'PAX', 'Paxos Standard Token', 'paxos-standard-token'),
  (35, 'TUSD', 'TrueUSD', 'trueusd'),
  (36, 'BTG', 'Bitcoin Gold', 'bitcoin-gold'),
  (37, 'HT', 'Huobi Token', 'huobi-token'),
  (38, 'BTM', 'Bytom', 'bytom'),
  (39, 'HEDG', 'HedgeTrade', 'hedgetrade'),
  (40, 'OMG', 'OmiseGO', 'omisego'),
  (41, 'RVN', 'Ravencoin', 'ravencoin'),
  (42, 'LSK', 'Lisk', 'lisk'),
  (43, 'NANO', 'Nano', 'nano'),
  (44, 'KCS', 'KuCoin Shares', 'kucoin-shares'),
  (45, 'BCD', 'Bitcoin Diamond', 'bitcoin-diamond'),
  (46, 'ALGO', 'Algorand', 'algorand'),
  (47, 'THETA', 'THETA', 'theta'),
  (48, 'INB', 'Insight Chain', 'insight-chain'),
  (49, 'WAVES', 'Waves', 'waves'),
  (50, 'BTT', 'BitTorrent', 'bittorrent'),
  (51, 'HOT', 'Holo', 'holo'),
  (52, 'NRG', 'Energi', 'energi'),
  (53, 'ICX', 'ICON', 'icon'),
  (54, 'DGB', 'DigiByte', 'digibyte'),
  (55, 'EGT', 'Egretia', 'egretia'),
  (56, 'ZRX', '0x', '0x'),
  (57, 'BTS', 'BitShares', 'bitshares'),
  (58, 'HC', 'HyperCash', 'hypercash'),
  (59, 'NPXS', 'Pundi X', 'pundi-x'),
  (60, 'REP', 'Augur', 'augur'),
  (61, 'AOA', 'Aurora', 'aurora'),
  (62, 'IOST', 'IOST', 'iostoken'),
  (63, 'MONA', 'MonaCoin', 'monacoin'),
  (64, 'NEX', 'Nash Exchange', 'nash-exchange'),
  (65, 'KMD', 'Komodo', 'komodo'),
  (66, 'DAI', 'Dai', 'dai'),
  (67, 'QNT', 'Quant', 'quant'),
  (68, 'MAID', 'MaidSafeCoin', 'maidsafecoin'),
  (69, 'SC', 'Siacoin', 'siacoin'),
  (70, 'XVG', 'Verge', 'verge'),
  (71, 'RIF', 'RIF Token', 'rif-token'),
  (72, 'ZIL', 'Zilliqa', 'zilliqa'),
  (73, 'AE', 'Aeternity', 'aeternity'),
  (74, 'GNT', 'Golem', 'golem-network-tokens'),
  (75, 'ETP', 'Metaverse ETP', 'metaverse'),
  (76, 'STEEM', 'Steem', 'steem'),
  (77, 'SNT', 'Status', 'status'),
  (78, 'ARDR', 'Ardor', 'ardor'),
  (79, 'REN', 'Ren', 'ren'),
  (80, 'QKC', 'QuarkChain', 'quarkchain'),
  (81, 'MCO', 'Crypto.com', 'crypto-com'),
  (82, 'GXC', 'GXChain', 'gxchain'),
  (83, 'ABBC', 'ABBC Coin', 'abbc-coin'),
  (84, 'ENJ', 'Enjin Coin', 'enjin-coin'),
  (85, 'WTC', 'Waltonchain', 'waltonchain'),
  (86, 'XZC', 'Zcoin', 'zcoin'),
  (87, 'SNX', 'Synthetix Network Token', 'synthetix-network-token'),
  (88, 'SOLVE', 'SOLVE', 'solve'),
  (89, 'WAX', 'WAX', 'wax'),
  (90, 'BEAM', 'Beam', 'beam'),
  (91, 'WAN', 'Wanchain', 'wanchain'),
  (92, 'STRAT', 'Stratis', 'stratis'),
  (93, 'ELF', 'aelf', 'aelf'),
  (94, 'ELA', 'Elastos', 'elastos'),
  (95, 'GRIN', 'Grin', 'grin'),
  (96, 'NEXO', 'Nexo', 'nexo'),
  (97, 'PAI', 'Project Pai', 'project-pai'),
  (98, 'ETN', 'Electroneum', 'electroneum'),
  (99, 'PZM', 'PRIZM', 'prizm')
